import { mkdir, readFile, writeFile, cp, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import MarkdownIt from 'markdown-it';
import { createHash } from 'node:crypto';

const base='https://lyrebird.alirezaafshan.com';
const papers=JSON.parse(await readFile('content/papers.json','utf8'));
const assetRevision=createHash('sha256').update(await readFile('public/assets/site.css')).update(await readFile('public/assets/site.js')).digest('hex').slice(0,12);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});
const compactDate=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'numeric'});
const bird='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M26 39c-7-1-11-5-10-11 1-5 5-7 9-5l4 3 6 1-6 3c-1 4-1 7-3 9Z" fill="currentColor"/><path d="M18 27C7 21 6 10 9 5c0 9 5 12 10 13M20 24C11 17 16 5 22 3c-4 7-2 12 1 15M24 23c-3-9 3-16 9-16-5 4-7 8-6 13M22 37l-4 7m7-6 2 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
const header=active=>`<a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/" aria-label="Lyrebird home">${bird}<span>lyrebird<span class="brand-small">Independent research</span></span></a><nav aria-label="Main navigation"><a href="/#library" ${active==='library'?'aria-current="page"':''}>Library</a><a href="/about/" ${active==='about'?'aria-current="page"':''}>About & standards</a><a class="author-link" href="https://alirezaafshan.com">Alireza Afshan <span aria-hidden="true">↗</span></a></nav></header>`;
const footer=`<footer class="wrap site-footer"><div><a class="footer-brand" href="/">lyrebird</a><p>A research library by Alireza Afshan.</p></div><p>Questions, methods, evidence.<br>Room to revise.</p><nav aria-label="Footer"><a href="/about/">Publication standards</a><a href="/feed.xml">RSS feed</a><a href="https://github.com/YesterdaysLemon/lyrebird">Source code ↗</a></nav><span class="copyright">© 2026 Alireza Afshan</span></footer>`;
function layout(title,description,body,{path='/',active='',meta=''}={}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Lyrebird</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${base+path}"><meta property="og:type" content="${path.startsWith('/papers/')?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${base+path}"><meta property="og:image" content="${base}/assets/social.svg"><meta name="theme-color" content="#f6f4ed"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="Lyrebird papers" href="/feed.xml"><link rel="stylesheet" href="/assets/site.css?v=${assetRevision}"><script defer src="/assets/site.js?v=${assetRevision}"></script>${meta}</head><body>${header(active)}${body}${footer}</body></html>`;}
async function put(path,text){const p=resolve('dist',path);await mkdir(dirname(p),{recursive:true});await writeFile(p,text);}
await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
await mkdir('dist/assets/fonts',{recursive:true});
for(const [pkg,prefix] of [['dm-sans','dm-sans'],['libre-baskerville','libre-baskerville']]){
  const files=await readdir(`node_modules/@fontsource/${pkg}/files`);
  for(const f of files.filter(x=>x.includes('-latin-')&&x.endsWith('.woff2')&&(x.includes('-400-normal')||x.includes('-500-normal')||x.includes('-700-normal')||x.includes('-400-italic')))) await cp(`node_modules/@fontsource/${pkg}/files/${f}`,`dist/assets/fonts/${f}`);
  await cp(`node_modules/@fontsource/${pkg}/LICENSE`,`dist/assets/fonts/${prefix}-LICENSE.txt`);
}

const topics=[...new Set(papers.map(p=>p.topic))];
const row=(p,i)=>`<article class="paper-row" data-paper data-topic="${esc(p.topic)}" data-search="${esc([p.title,p.summary,p.topic,p.type,p.project].join(' ').toLowerCase())}"><div class="paper-number">${String(i+1).padStart(2,'0')}<span>${esc(compactDate(p.date))}</span></div><div class="paper-main"><div class="eyebrow">${esc(p.topic)} <span class="dot">·</span> ${esc(p.type)}</div><h3><a href="/papers/${p.slug}/">${esc(p.title)}<span class="row-arrow" aria-hidden="true">↗</span></a></h3><p>${esc(p.summary)}</p><div class="paper-tags"><span>${esc(p.evidence)}</span><span>${esc(p.project)}</span></div></div></article>`;
const featured=papers[0];
const home=`<main id="main"><section class="hero wrap"><div class="hero-kicker"><span class="small-rule"></span> An independent collection <span class="edition">Vol. 01 / 2026</span></div><div class="hero-grid"><h1>Research,<br>in the open<span class="accent">.</span></h1><div class="hero-note"><p>How models learn. What experiments reveal. Where a proof stops.</p><p class="muted">Papers and research notes by Alireza Afshan, with methods, results, and the limits that give them meaning.</p><a class="text-link" href="#library">Explore the library <span aria-hidden="true">↓</span></a></div></div></section><section class="featured wrap" aria-labelledby="featured-title"><div class="featured-art" aria-hidden="true"><div class="cache-title">CONTEXT → MEMORY</div><div class="cache-grid">${Array.from({length:72},(_,i)=>`<i class="${i%7===0||i>59?'retain':i%3===0?'faint':''}"></i>`).join('')}</div><div class="cache-legend"><span><i></i> Keep what matters</span><span>KV / 01</span></div></div><div class="featured-copy"><div class="eyebrow">Latest paper <span class="dot">·</span> ${esc(featured.type)}</div><h2 id="featured-title"><a href="/papers/${featured.slug}/">${esc(featured.title)}</a></h2><p>${esc(featured.summary)}</p><a class="text-link" href="/papers/${featured.slug}/">Read the paper <span aria-hidden="true">↗</span></a></div></section><section id="library" class="library wrap" aria-labelledby="library-title"><div class="section-heading"><div class="eyebrow">The collection</div><h2 id="library-title">Papers & notes <sup>${String(papers.length).padStart(2,'0')}</sup></h2><p>Completed work, including results that complicate the idea.</p></div><form class="library-tools" role="search"><label class="search-label" for="search">Search the collection<input id="search" type="search" placeholder="Search titles, topics, methods…" autocomplete="off"></label><label for="topic">Research area<select id="topic"><option value="">All areas</option>${topics.map(t=>`<option>${esc(t)}</option>`).join('')}</select></label></form><div class="result-count" id="result-count" aria-live="polite">${papers.length} papers and notes</div><div id="paper-list">${papers.map(row).join('')}</div><div id="empty" class="empty" hidden><h3>No papers match that search.</h3><p>Try a broader term, or clear the filters.</p><button id="reset-filters" type="button">Clear filters</button></div></section><aside class="standards-banner wrap"><span class="eyebrow">A note on the collection</span><p>A small experiment can be worth sharing.<br>Its claims should stay the same size as its evidence.</p><a class="text-link" href="/about/">How papers are selected <span aria-hidden="true">↗</span></a></aside></main>`;
await put('index.html',layout('Research, in the open','Papers and research notes by Alireza Afshan on machine learning, model behavior, optimization, and mathematics.',home,{active:'library'}));

for(const [index,p] of papers.entries()){
  let source=await readFile(`content/${p.slug}.md`,'utf8');
  source=source.replace(/^# .+\r?\n/,'');
  const md=new MarkdownIt({html:false,linkify:true,typographer:true});
  const oldLink=md.renderer.rules.link_open;
  md.renderer.rules.link_open=(tokens,i,options,env,self)=>{const t=tokens[i];let href=t.attrGet('href');if(href&&!/^(https?:|mailto:|#|\/)/.test(href))t.attrSet('href',new URL(href,p.sourceBase).href);return oldLink?oldLink(tokens,i,options,env,self):self.renderToken(tokens,i,options);};
  const toks=md.parse(source,{});const toc=[];const slugs=new Map();
  for(const token of toks){const style=token.attrGet('style');if(style?.startsWith('text-align:')){token.attrs=token.attrs.filter(([name])=>name!=='style');token.attrSet('class','align-'+style.split(':')[1].trim());}}
  for(let i=0;i<toks.length;i++)if(toks[i].type==='heading_open'){
    const txt=toks[i+1].content;let id=txt.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let n=slugs.get(id)||0;slugs.set(id,n+1);if(n)id+='-'+(n+1);toks[i].attrSet('id',id);if(toks[i].tag==='h2')toc.push({id,txt});
  }
  const html=md.renderer.render(toks,md.options,{});
  const bib=`@misc{afshan2026${p.slug.replace(/-/g,'')},\n  author = {Afshan, Alireza},\n  title = {${p.title}},\n  year = {2026},\n  howpublished = {Lyrebird, ${p.type.toLowerCase()}},\n  url = {${base}/papers/${p.slug}/},\n  note = {Version ${p.version}. Not peer reviewed.}\n}\n`;
  await put(`papers/${p.slug}/citation.bib`,bib);
  await put(`papers/${p.slug}/paper.md`,await readFile(`content/${p.slug}.md`));
  const paper=`<main id="main" class="paper-page wrap"><a class="back" href="/#library">← The library</a><header class="paper-header"><div class="eyebrow">${esc(p.topic)} <span class="dot">·</span> ${esc(p.type)} <span class="paper-id">LYR–${String(index+1).padStart(3,'0')}</span></div><h1>${esc(p.title)}</h1><p class="paper-deck">${esc(p.summary)}</p><div class="byline"><span>Alireza Afshan</span><span>${date(p.date)}</span><span>Version ${p.version}</span></div><div class="paper-actions"><a class="button primary" href="/papers/${p.slug}/paper.pdf">Read PDF <span aria-hidden="true">↗</span></a><a class="button" href="${esc(p.source)}">Code & evidence ↗</a><button class="button" data-cite="${p.slug}" type="button">Copy citation</button><a class="quiet-link" href="/papers/${p.slug}/citation.bib">BibTeX ↓</a><span class="copy-status" role="status"></span></div></header><div class="paper-layout"><aside class="paper-aside"><div class="status-note"><span class="eyebrow">Evidence status</span><strong>${esc(p.evidence)}</strong><p>${esc(p.limit)}</p><span class="review-status">Not peer reviewed</span></div><nav class="toc" aria-label="On this page"><span class="eyebrow">On this page</span>${toc.map(t=>`<a href="#${t.id}">${esc(t.txt)}</a>`).join('')}</nav></aside><article class="prose">${html}<section class="publication-record" id="publication-record"><h2>Publication record</h2><p>This edition was selected for Lyrebird on September 22, 2026. ${esc(p.editionNote||'The source manuscript is preserved with its original scope. Relative evidence links resolve to the source repository.')}</p><p>Research assistance: Codex. Alireza Afshan is the project owner and named author; assistance is disclosed and does not constitute independent review. No journal acceptance or DOI is claimed.</p><p><a href="${esc(p.source)}">Versioned source and supporting records</a> · <a href="paper.md">Download Markdown</a> · <a href="citation.bib">Download BibTeX</a></p></section></article></div><nav class="paper-next" aria-label="More research"><span class="eyebrow">Continue reading</span>${papers.filter(q=>q.slug!==p.slug).slice(0,2).map(q=>`<a href="/papers/${q.slug}/">${esc(q.title)} <span>↗</span></a>`).join('')}</nav></main>`;
  const meta=`<meta name="citation_title" content="${esc(p.title)}"><meta name="citation_author" content="Afshan, Alireza"><meta name="citation_publication_date" content="${p.date.replaceAll('-','/')}"><meta name="citation_pdf_url" content="${base}/papers/${p.slug}/paper.pdf"><meta name="citation_technical_report_institution" content="Independent research"><meta name="citation_language" content="en">`;
  await put(`papers/${p.slug}/index.html`,layout(p.title,p.summary,paper,{path:`/papers/${p.slug}/`,meta}));
}
const about=`<main id="main" class="about wrap"><div class="eyebrow">About the library</div><h1>Curiosity, with<br>a paper trail<span class="accent">.</span></h1><div class="about-grid"><p class="about-intro">Lyrebird is the research library of Alireza Afshan. It brings together experiments and mathematical work that would otherwise live in separate project folders.</p><div class="prose"><h2>What belongs here</h2><p>A paper needs a concrete question, inspectable methods or proof, a completed result, and an honest account of what that result cannot establish. Negative results and small studies belong when their limits are useful and visible.</p><p>This first collection covers machine learning, model behavior, optimization, and graph theory. Selection is editorial judgment, not a claim of journal acceptance.</p><h2>Read the label</h2><p><strong>Preprint</strong> denotes a developed manuscript shared before formal review. <strong>Research note</strong> denotes a bounded completed experiment. <strong>Mathematical note</strong> denotes a written theorem or argument with its scope and supporting checks. A <strong>pilot study</strong> tests a research direction at limited scale.</p><p>All papers currently in this collection are <strong>not peer reviewed</strong>. Tests, reproducible scripts, and agent audits help inspect a claim; they do not stand in for independent scientific review.</p><h2>AI assistance and authorship</h2><p>These projects use Codex for research assistance, implementation, analysis, and drafting. Individual papers disclose relevant evaluation and review arrangements. Alireza Afshan directs the research and is the named project owner. Model-generated explanations and ratings carry the limitations stated in each paper.</p><h2>Versions, citations, and corrections</h2><p>Every entry includes a dated edition, PDF, citation, and link to source records. Changes that alter a finding should produce a new version and an explanation in its publication record. Source commits identify the evidence used for this collection.</p><p>Lyrebird assigns no DOI and implies no institutional affiliation. Cite the author, title, date, version, and stable paper URL. Source software and datasets retain their own licenses; publication here does not relicense them.</p><h2>Contact</h2><p>Find Alireza’s current contact channels and other work at <a href="https://alirezaafshan.com">alirezaafshan.com</a>. For a correction to this library, <a href="https://github.com/YesterdaysLemon/lyrebird/issues">open an issue on GitHub</a> with the paper and the specific claim or evidence at issue.</p><h2>Privacy</h2><p>This site uses no analytics, advertising scripts, cookies, or visitor accounts. Search runs in your browser. Hosting providers may retain ordinary request logs.</p></div></div></main>`;
await put('about/index.html',layout('About & publication standards','How Lyrebird selects, labels, and preserves independent research.',about,{path:'/about/',active:'about'}));
await put('404.html',layout('Page not found','Return to the Lyrebird research library.',`<main id="main" class="wrap error-page"><div class="eyebrow">404 / A missing page</div><h1>This branch is empty.</h1><p>The paper may have moved, or this address may be incomplete.</p><a class="button primary" href="/#library">Return to the library →</a></main>`));
await put('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/about/',...papers.map(p=>`/papers/${p.slug}/`)].map(path=>`<url><loc>${base+path}</loc></url>`).join('')}</urlset>`);
await put('feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Lyrebird · Alireza Afshan</title><link>${base}</link><description>Independent papers and research notes</description>${papers.map(p=>`<item><title>${esc(p.title)}</title><link>${base}/papers/${p.slug}/</link><guid>${base}/papers/${p.slug}/</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(p.summary)}</description></item>`).join('')}</channel></rss>`);
await put('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
let sha=process.env.BUILD_SHA;
if(!sha||sha==='unknown')try{
  const head=(await readFile('.git/HEAD','utf8')).trim();
  if(head.startsWith('ref: ')){
    const ref=head.slice(5);
    try{sha=(await readFile('.git/'+ref,'utf8')).trim();}catch{const packed=await readFile('.git/packed-refs','utf8');sha=packed.split('\n').find(line=>line.endsWith(' '+ref))?.split(' ')[0];}
  }else sha=head;
}catch{sha='local';}
if(!/^[0-9a-f]{40}$/.test(sha||''))sha='local';
await put('version.json',JSON.stringify({app:'lyrebird',sha,papers:papers.length}));
await put('catalog.json',JSON.stringify(papers.map(({slug,title,summary,date,topic,type,version,source,evidence,limit})=>({slug,title,summary,date,topic,type,version,source,evidence,limit})),null,2));
console.log(`Built Lyrebird: ${papers.length} papers, ${sha}`);
